### ISSUE TITLE
Set up Gradle for compilation and build tasks

### ISSUE THREAD

**Issue by aelnourSLU** [Regorh/Stock-Market-Simulator#14]
As a designer I want to set up gradle so that compiling and error testing is easier in Java. I want to do this because I think it eill make out workflow fast and easier

**Comment by aelnourSLU** [comment]
After review, the new layout appears to work just fine. Gradle appears to be implemented and the MVC structuring for the project remains intact. Looks good here.

**Comment by aelnourSLU** [comment]
Accidentally closed issue; reopening

**Comment by Omp06** [comment]
After reviewing this pull request, I believe that the Gradle works fine and looks ready for further development.
