### ISSUE TITLE
Broad Description of project

### ISSUE THREAD

**Issue by nguzinski** [Regorh/Stock-Market-Simulator#2]
As A Developer, I want a a broad description of the game,  a high level of how it works, key mechanics, and I want it in the ReadMe, So that as we work more on the project we have guiderails for our end goal, and so everyone is on the same page

**Comment by Omp06** [comment]
I believe that Noah did a well job of having a broad description of the game in mind. When I was discussing the idea of the game with him while completing the high level document, I was able to easily help understand his thought process and ideas for the game. It allowed me to finish the high level documentation efficiently and descriptively.
