### ISSUE TITLE
Create UML for initial class structure

### ISSUE THREAD

**Issue by aelnourSLU** [Regorh/Stock-Market-Simulator#5]
As A designer, I want a UML diagram of the class structure/scaffold, it shall include, Game, User, Market, Stock, Event per year, Algorithm, Event log, Pressure/stress, FCC, Opponent company/mob/aggressor/debt collector(TBD). so that we can easily add code and understand the high level system as we develop further

**Comment by nguzinski** [comment]
lgtm, great for team sync, and understanding
