### ISSUE TITLE
Initialize Kanban Board

### ISSUE THREAD

**Issue by aelnourSLU** [Regorh/Stock-Market-Simulator#9]
- [x] Create and distribute story point labels
As a Developer, I want to create a Kanban board with what we need to do, what we are doing, and what we have done, so that the team understands the workflow

**Comment by Omp06** [comment]
I believe Ali did a proper job of creating the Kanban board. It has all the labels as we deemed necessary as a group. It was also created in a timely manner for us to begin the bigger issues in Sprint 1.
